- hosts: localhost
  gather_facts: no
  become: true

  vars:
    ondemand_version: 3.0.3
  tasks:
  - name: Wait 300 seconds for the nodes to be ready
    wait_for_connection:
      timeout: 300
  - name: Gather facts for first time
    setup:
