- hosts: localhost
  gather_facts: no
  become: true

  vars:
    ondemand_version: 3.1.7
    ood_package: "{{ ('ondemand=' if ( ansible_distribution == 'Ubuntu') else 'ondemand-') }}{{ondemand_version}}"
  tasks:
  - name: Wait 300 seconds for the nodes to be ready
    wait_for_connection:
      timeout: 300
  - name: Gather facts for first time
    setup:

  - name: set httpd_auth values when using basic auth
    set_fact:
      httpd_auth:
        - AuthType Basic
        - AuthName "Open OnDemand"
        - AuthBasicProvider external
        - AuthExternal pwauth
        - Require valid-user

  - name: Make sure we have the latest root certificates in AlmaLinux
    yum:
      name: ca-certificates
      state: latest
      lock_timeout : 180
    when: 
      - ansible_distribution == 'AlmaLinux'

  - name: Make sure we have the latest root certificates in Ubuntu
    apt:
      name: ca-certificates
      state: latest
    when: ansible_distribution == 'Ubuntu'

  - name: Set up PAM authentication for OOD
    include_role:
      name: ood_pam_auth

  - name: Generate a Self Signed OpenSSL certificate
    shell: |
      mkdir -pv /etc/ssl/{{ ansible_default_ipv4.address }}
      cd /etc/ssl/{{ ansible_default_ipv4.address }}
      openssl req -nodes -new -x509 -keyout {{ ansible_default_ipv4.address }}.key -out {{ ansible_default_ipv4.address }}.crt -subj "/CN={{ ansible_default_ipv4.address }}"
    args:
      creates: "/etc/ssl/{{ ansible_default_ipv4.address }}/{{ ansible_default_ipv4.address }}.crt"

  - name: Run the ood-ansible role for HTTPS
    include_role:
      name: ood-ansible
    vars:
      ondemand_package: '{{ ood_package }}'
      servername: '{{ ansible_default_ipv4.address }}'
      httpd_port: 443
      ssl:
      - SSLCertificateFile "/etc/ssl/{{ ansible_default_ipv4.address }}/{{ ansible_default_ipv4.address }}.crt"
      - SSLCertificateKeyFile "/etc/ssl/{{ ansible_default_ipv4.address }}/{{ ansible_default_ipv4.address }}.key"
      - "{{SSLCertificateChainFile | default(None)}}"
      - SSLProtocol all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
      - SSLCipherSuite ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256

  - name: activate new apache2 configuration in Ubuntu
    service:
      name: apache2
      state: reloaded
    when: ansible_distribution == 'Ubuntu'

  # temporary workaround waiting for this https://github.com/OSC/ood-ansible/issues/222
  - name: Configure pwauth for Apache
    blockinfile:
      path: /opt/ood/ood-portal-generator/templates/ood-portal.conf.erb
      insertafter: OOD_PUN_STAGE_CMD
      marker: "# {mark} ANSIBLE MANAGED BLOCK - Configure pwauth for Apache"
      block: |
          AddExternalAuth pwauth /usr/bin/pwauth
          SetExternalAuthMethod pwauth pipe
    when: 
      - ansible_distribution in ['AlmaLinux']

  # temporary workaround waiting for this https://github.com/OSC/ood-ansible/issues/222
  - name: Configure pwauth for Apache
    blockinfile:
      path: /opt/ood/ood-portal-generator/templates/ood-portal.conf.erb
      insertafter: OOD_PUN_STAGE_CMD
      marker: "# {mark} ANSIBLE MANAGED BLOCK - Configure pwauth for Apache"
      block: |
          AddExternalAuth pwauth /usr/sbin/pwauth
          SetExternalAuthMethod pwauth pipe
    when: 
      - ansible_distribution in ['Ubuntu']

  - name: Ensure apache is restarted
    service: 
      name: httpd
      state: restarted
      enabled: yes
    when: 
      - ansible_distribution == 'AlmaLinux'
      - ansible_distribution_major_version == '8'

  - name: Generate new ood_portal.conf file
    shell: /opt/ood/ood-portal-generator/sbin/update_ood_portal -f
    when: 
      - ansible_distribution == 'Ubuntu'

  - name: Ensure apache is restarted
    service: 
      name: apache2
      state: restarted
      enabled: yes
    when: 
      - ansible_distribution == 'Ubuntu'

  - name: Install NFS dependencies packages for Ubuntu
    apt:
      name: nfs-common
      state: latest
    when: ansible_distribution == 'Ubuntu'

  - name: Install NFS dependencies packages for AlmaLinux
    yum:
      name: nfs-utils
      state: latest
      lock_timeout : 180
    when: ansible_distribution == 'AlmaLinux'